site_name: The Morpheus Tutorials Resources
site_url: https://resources.the-morpheus.de/
repo_name: themorpheustutorials/resources
repo_url: https://github.com/themorpheustutorials/resources
site_description: "Resources from the community, for the community."
site_author: https://github.com/themorpheustutorials
remote_branch: main
edit_uri: edit/main/docs

theme:
  name: 'material'
  palette:
    scheme: preference
    primary: 'green'
    accent: 'lime'

  font:
    text: Roboto
    code: Roboto Mono

  language: en
  direction: ltr
  icon:
    repo: fontawesome/brands/github

  features:
    - search.suggest
    - search.highlight
    - navigation.expand
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true

plugins:
  - git-revision-date
  - search:
      lang: de

nav:
  - 'Allgemeines': index.md
  - 'Blogs':
      - 'Allgemeine Blogs': blogs/index.md
      - 'Python': blogs/python.md
      - 'Web Entwicklung (Client)': blogs/web-client.md
  - 'Software':
      - 'Software Engenering': software/software-engenering.md
      - 'Tools': software/tools.md
      - 'AI': software/ai.md
      - 'BSD': software/bsd.md
      - 'Linux': software/linux.md
      - 'Search Engines': software/search-engines.md
      - 'Windows': software/windows.md
      - 'WebDev': software/webdev.md
  - 'Hardware':
      - 'PC Hardware': hardware/pc.md
      - 'Arduino': hardware/arduino.md
      - 'Raspberry PI': hardware/raspberry-pi.md
      - 'Elektrotechnik': hardware/elektrotechnik.md
  - 'IT-Security': it-security.md
  - 'Netzwerktechnik': netzwerktechnik.md
  - 'Mathematik': mathematik.md
  - 'BÃ¼cher': books.md
  - 'Privacy': privacy.md
